# Generated by Django 2.1.1 on 2018-09-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empArr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrival_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Contact', models.IntegerField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('About', models.TextField()),
                ('portfolio_site', models.URLField()),
                ('registered', models.BooleanField()),
                ('date_of_birth', models.DateField()),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=5, max_digits=10)),
                ('membership_valid', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='emparr',
            name='Emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee'),
        ),
    ]
